In [184]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import  pandas as pd 
import json 
import os
from glob import glob
import seaborn as sns 
import numpy as np 
import re
import tikzplotly
import plotly.express as px
from IPython.display import display
from PIL import Image
import matplotlib as mpl
import matplotlib.pyplot as plt 
import plotly 
import plotly.graph_objects as go

from IPython.display import IFrame

from utils.benchmark import * 
import tikzplotly

In [185]:
notebook_name="05-multileader"
os.makedirs(f"outputs/{notebook_name}", exist_ok=True)

In [186]:
folder = "../../aws/benchmark/out/geobft/final-multileader-geobft-with-non-optimistic-global-sharing-2-buckets/" 
benchmarks = glob(f"{folder}*/")

In [187]:

throughputs = process_throughput_benchmarks(benchmarks)
throughputs["files"] = throughputs["benchmark"]
throughputs["benchmark"] = "multileader non-optimistic-2-buckets"
throughputs["buckets"] = 2 
throughputs["num_peers"] = throughputs["num_peers"]/throughputs["number_of_clusters"]
processed_cpu_usage = process_cpu_usage(benchmarks)
processed_cpu_usage["num_peers"] = processed_cpu_usage["num_peers"]/processed_cpu_usage["number_of_clusters"]
processed_cpu_usage["files"] = processed_cpu_usage["benchmark"]
processed_cpu_usage["benchmark"] = "multileader non-optimistic-2-buckets"
processed_cpu_usage["buckets"] = 2 

bytes_sent = process_bytes_sent(benchmarks)
bytes_sent["files"] = bytes_sent["benchmark"]
bytes_sent["benchmark"] =  "multileader non-optimistic-2-buckets"
bytes_sent["buckets"] = 2 

bytes_sent["num_peers"] = bytes_sent["num_peers"]/bytes_sent["number_of_clusters"]
bytes_sent_in_gbps = (bytes_sent.groupby(["num_peers","vallen","role","number_of_clusters","cluster_batch_size","benchmark","files"])[["bytes_sent"]].sum() * 8 * 10**(-9) * 15**(-1)).reset_index()
bytes_sent_in_gbps["bytes_sent"] = bytes_sent_in_gbps["bytes_sent"] / bytes_sent_in_gbps["number_of_clusters"]
bytes_sent_in_gbps["files"] = bytes_sent_in_gbps["benchmark"]
bytes_sent_in_gbps["benchmark"] =  "multileader non-optimistic-2-buckets"
bytes_sent_in_gbps["buckets"] = 2

In [188]:
folder = "../../aws/benchmark/out/geobft/final-multileader-geobft-with-non-optimistic-global-sharing-4-buckets/" 
benchmarks = glob(f"{folder}*/")

In [189]:

throughputs4 = process_throughput_benchmarks(benchmarks)
throughputs4["files"] = throughputs4["benchmark"]
throughputs4["benchmark"] = "multileader non-optimistic-4-buckets"
throughputs4["buckets"] = 4 
throughputs4["num_peers"] = throughputs4["num_peers"]/throughputs4["number_of_clusters"]
processed_cpu_usage4 = process_cpu_usage(benchmarks)
processed_cpu_usage4["num_peers"] = processed_cpu_usage4["num_peers"]/processed_cpu_usage4["number_of_clusters"]
processed_cpu_usage4["files"] = processed_cpu_usage4["benchmark"]
processed_cpu_usage4["benchmark"] = "multileader non-optimistic-4-buckets"
processed_cpu_usage4["buckets"] = 4 

bytes_sent4 = process_bytes_sent(benchmarks)
bytes_sent4["files"] = bytes_sent4["benchmark"]
bytes_sent4["benchmark"] =  "multileader non-optimistic-4-buckets"
bytes_sent4["buckets"] = 4 

bytes_sent4["num_peers"] = bytes_sent4["num_peers"]/bytes_sent4["number_of_clusters"]
bytes_sent_in_gbps4 = (bytes_sent4.groupby(["num_peers","vallen","role","number_of_clusters","cluster_batch_size","benchmark","files"])[["bytes_sent"]].sum() * 8 * 10**(-9) * 15**(-1)).reset_index()
bytes_sent_in_gbps4["bytes_sent"] = bytes_sent_in_gbps4["bytes_sent"] / bytes_sent_in_gbps4["number_of_clusters"]
bytes_sent_in_gbps4["files"] = bytes_sent_in_gbps4["benchmark"]
bytes_sent_in_gbps4["benchmark"] =  "multileader non-optimistic-4-buckets"
bytes_sent_in_gbps4["buckets"] = 4

In [190]:
throughputs = pd.concat([throughputs,throughputs4],ignore_index=True)
processed_cpu_usage = pd.concat([processed_cpu_usage,processed_cpu_usage4],ignore_index=True)
bytes_sent_in_gbps = pd.concat([bytes_sent_in_gbps,bytes_sent_in_gbps4],ignore_index=True)
bytes_sent = pd.concat([bytes_sent,bytes_sent4],ignore_index=True)

In [191]:
previous_throughputs = pd.read_json(f"outputs/03-geobft-alternating/throughputs.json",orient="records")
notaltnonopt = previous_throughputs.query("benchmark == 'not-alternating-non-optimistic' and alternating == False")
previous_throughputs = previous_throughputs.groupby(["number_of_clusters","cluster_batch_size","num_peers","vallen"]).max().reset_index().query("cluster_batch_size < 256")
previous_throughputs["benchmark"] = "max"
previous_throughputs = pd.concat([previous_throughputs,notaltnonopt],ignore_index=True)
previous_throughputs["buckets"] = 1

In [192]:
previous_throughputs.query("num_peers == 3 and number_of_clusters == 2 and vallen == 512")

,number_of_clusters,cluster_batch_size,num_peers,vallen,benchmark,throughput,runtime,alternating,nonoptimistic,files,buckets
0,2,1,3,512,max,2158.521851,10.000758,True,True,../../aws/benchmark/out/geobft/final-geobft-no...,1
4,2,16,3,512,max,15435.375000,10.001387,True,True,../../aws/benchmark/out/geobft/final-geobft-no...,1
8,2,64,3,512,max,22577.202148,10.001052,True,True,../../aws/benchmark/out/geobft/final-geobft-no...,1
12,2,128,3,512,max,23650.868164,10.001103,True,True,../../aws/benchmark/out/geobft/final-geobft-no...,1
66,2,64,3,512,not-alternating-non-optimistic,22065.051758,10.000467,False,True,../../aws/benchmark/out/geobft/final-geobft-no...,1
68,2,128,3,512,not-alternating-non-optimistic,23650.868164,10.001024,False,True,../../aws/benchmark/out/geobft/final-geobft-no...,1
70,2,256,3,512,not-alternating-non-optimistic,24063.232422,10.000239,False,True,../../aws/benchmark/out/geobft/final-geobft-no...,1
84,2,1,3,512,not-alternating-non-optimistic,2120.243408,10.000758,False,True,../../aws/benchmark/out/geobft/final-geobft-no...,1
86,2,16,3,512,not-alternating-non-optimistic,14500.819824,10.001387,False,True,../../aws/benchmark/out/geobft/final-geobft-no...,1

In [193]:
throughputs = pd.concat([throughputs,previous_throughputs],ignore_index=True)

In [194]:
grouped = throughputs.query("cluster_batch_size < 256").groupby(["num_peers","number_of_clusters"])
for gr, g in grouped:
    fig  = go.Figure()
    for v,data in g.sort_values(["cluster_batch_size","vallen","benchmark"]).groupby(["vallen","buckets","benchmark"]):
        # different dashes for benchmarks 
        # display(data)
        
        fig.add_trace(go.Scatter(
            name=f"vallen: {v[0]} - buckets: {v[1]} - {v[2]}",
            x=data["cluster_batch_size"],
            y=data["throughput"],
            mode='lines+markers',
            line=dict(dash='solid' if v[1]==2 else 'dash'),
            marker=dict(symbol='circle' if v[1]==2 else 'square'),
            
            
        ))
    fig.update_layout(
        title=f"GeoBFT Throughput vs Cluster Batch Size - Num Peers per Cluster: {gr[0]} - Number of Clusters: {gr[1]}",
        xaxis_title="Cluster Batch Size",
        yaxis_title="Throughput (tx/s)",
        barmode='group'
    )
    fig.show()
    tikzplotly.save(filepath=f"outputs/{notebook_name}/geobft-throughput-numpeers-{gr[0]}-clusterbatchsize-{gr[1]}.tex",fig=fig)

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

In [195]:
cpuusage = pd.read_json(f"outputs/03-geobft-alternating/cpu_usage.json",orient="records")
cpuusage = cpuusage.query("benchmark == 'not-alternating-non-optimistic' and alternating == False")
# cpuusage = pd.concat([cpuusage,notaltnonopt],ignore_index=True)
cpuusage["buckets"] = 1 

grouped = pd.concat([processed_cpu_usage,cpuusage]).query("cluster_batch_size < 256 and role > 0 ").groupby(["num_peers","number_of_clusters","role"])
for gr, g in grouped:
    fig  = go.Figure()
    for v,data in g.sort_values(["cluster_batch_size","vallen","benchmark"]).groupby(["vallen","benchmark","buckets"]):
        # different dashes for benchmarks 
        # display(data)
        
        fig.add_trace(go.Scatter(
            name=f"vallen: {v[0]} - {v[1]} - buckets: {v[2]}",
            x=data.groupby(["benchmark","cluster_batch_size"])["cluster_batch_size"].mean(),
            y=data.groupby(["benchmark","cluster_batch_size"])["cpu_usage"].mean(),
            error_y=dict(
                type='data',
                array=data.groupby(["benchmark","cluster_batch_size"])["cpu_usage"].std(),
                visible=True
            ),
            mode='lines+markers',
            line=dict(dash='solid' if v[2]==2 else ('dash' if v[2]==4 else 'dot'))
        ))
    fig.update_layout(
        title=f"GeoBFT - cpu_usage - numpeers={gr[0]} - numberofclusters={gr[1]} - role={gr[2]}",
        xaxis_title="Cluster Batch Size",
        yaxis_title="cpu_usage in percent",
        barmode='group'
    )
    fig.show()
    tikzplotly.save(filepath=f"outputs/{notebook_name}/geobft-cpuusage-numpeers-{gr[0]}-clusterbatchsize-{gr[1]}-role-{gr[2]}.tex",fig=fig)

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

In [196]:
bytes_sent_gbpsone = pd.read_json(f"outputs/03-geobft-alternating/bytes_sent_gbps.json",orient="records")
bytes_sent_gbpsone = bytes_sent_gbpsone.query("benchmark == 'not-alternating-non-optimistic' and alternating == False")
# bytes_sent_gbps = pd.concat([bytes_sent_gbps,notaltnonopt],ignore_index=True)
bytes_sent_gbpsone["buckets"] = 1 

grouped = pd.concat([bytes_sent_gbpsone,bytes_sent_in_gbps]).query("cluster_batch_size < 256 and role > 0 ").groupby(["num_peers","number_of_clusters","role"])

In [197]:

grouped = pd.concat([bytes_sent_gbpsone,bytes_sent_in_gbps]).query("cluster_batch_size < 256 and role > 0 ").groupby(["num_peers","number_of_clusters","role"])
for gr, g in grouped:
    fig  = go.Figure()
    for v,data in g.sort_values(["cluster_batch_size","vallen","benchmark"]).groupby(["vallen","benchmark","buckets"]):
        # different dashes for benchmarks 
        # display(data)
        
        fig.add_trace(go.Scatter(
            name=f"vallen: {v[0]} - {v[1]} - buckets: {v[2]}",
            x=data.groupby(["benchmark","cluster_batch_size"])["cluster_batch_size"].mean(),
            y=data.groupby(["benchmark","cluster_batch_size"])["bytes_sent"].mean(),
            mode='lines+markers',
            line=dict(dash='solid' if v[2]==2 else ('dash' if v[2]==4 else 'dot'))
        ))
    fig.update_layout(
        title=f"GeoBFT - bytes_sent_in_gbps - numpeers={gr[0]} - numberofclusters={gr[1]} - role={gr[2]}",
        xaxis_title="Cluster Batch Size",
        yaxis_title="Bytes Sent in Gbps",
        barmode='group'
    )
    fig.show()
    tikzplotly.save(filepath=f"outputs/{notebook_name}/geobft-bytes-sent-gbps-numpeers-{gr[0]}-clusterbatchsize-{gr[1]}-role-{gr[2]}.tex",fig=fig)

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

/home/andre/miniconda3/lib/python3.13/site-packages/tikzplotly/_axis.py:149: UserWarning:

The categoryorder option is not supported (yet 🤞) for the axis environment.

In [198]:
bytes_sentone = pd.read_json(f"outputs/03-geobft-alternating/bytes_sent.json",orient="records")
bytes_sentone = bytes_sentone.query("benchmark == 'not-alternating-non-optimistic' and alternating == False")
# bytes_sent = pd.concat([bytes_sent,notaltnonopt],ignore_index=True)
bytes_sentone["buckets"] = 1 

grouped = pd.concat([bytes_sentone,bytes_sent]).query("cluster_batch_size < 256 and role > 0 ").groupby(["num_peers","number_of_clusters","role"])

In [199]:
pd.concat([bytes_sentone,bytes_sent])

,benchmark,num_peers,vallen,runtime,typ,bytes_sent,role,cluster_batch_size,number_of_clusters,alternating,nonoptimistic,files,cluster_num_peers,buckets
0,not-alternating-non-optimistic,24.0,512,NaN,ClusterPrepare,2.845528e+08,2,128,4,False,True,../../aws/benchmark/out/geobft/final-geobft-no...,6.0,1
1,not-alternating-non-optimistic,24.0,512,NaN,PrePrepare,1.038254e+08,2,128,4,False,True,../../aws/benchmark/out/geobft/final-geobft-no...,6.0,1
2,not-alternating-non-optimistic,24.0,512,NaN,Checkpoint,2.884350e+04,2,128,4,False,True,../../aws/benchmark/out/geobft/final-geobft-no...,6.0,1
3,not-alternating-non-optimistic,24.0,512,NaN,Prepare,1.450858e+07,2,128,4,False,True,../../aws/benchmark/out/geobft/final-geobft-no...,6.0,1
4,not-alternating-non-optimistic,24.0,512,NaN,Commit,1.338390e+07,2,128,4,False,True,../../aws/benchmark/out/geobft/final-geobft-no...,6.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15451,multileader non-optimistic-4-buckets,6.0,4096,None,ClusterPrePrepare,3.037115e+05,1,120,2,False,True,../../aws/benchmark/out/geobft/final-multilead...,NaN,4
15452,multileader non-optimistic-4-buckets,6.0,4096,None,Prepare,1.868123e+07,1,120,2,False,True,../../aws/benchmark/out/geobft/final-multilead...,NaN,4
15453,multileader non-optimistic-4-buckets,6.0,4096,None,PrePrepare,0.000000e+00,1,120,2,False,True,../../aws/benchmark/out/geobft/final-multilead...,NaN,4
15454,multileader non-optimistic-4-buckets,6.0,4096,None,Commit,1.718031e+07,1,120,2,False,True,../../aws/benchmark/out/geobft/final-multilead...,NaN,4
15455,multileader non-optimistic-4-buckets,6.0,4096,None,ClientResponse,2.442792e+06,1,120,2,False,True,../../aws/benchmark/out/geobft/final-multilead...,NaN,4

In [200]:
bytes_sent["cluster_num_peers"] = bytes_sent["num_peers"] 
for (group,df) in pd.concat([bytes_sentone,bytes_sent]).groupby(['cluster_num_peers']): 
    # display(df)
    # continue
    role_df = get_role_df(df, role=2)
    role_df = add_combined_column(role_df, ['vallen','number_of_clusters',"benchmark"], 'num_peers_vallen')
    role_df_complete = complete_multiindex(role_df, ['typ', 'vallen','number_of_clusters',"num_peers_vallen"])

    role_df_complete = add_percent_column(role_df_complete, 'num_peers_vallen', 'bytes_sent', 'bytes_sent_percent')
    cluster_num_peers = group[0]
    print(f"Cluster Num Peers: {cluster_num_peers}")
    
     


    plot_tikz(
        role_df_complete,
        x_col="num_peers_vallen",
        y_col="bytes_sent_percent",
        cat_col="typ",
        filename=f"outputs/{notebook_name}/geobft-spread-over-azs-bytes-sent-role2-{cluster_num_peers}.tex",
        xlabel="(Number of Peers, Vallen)",
        ylabel="Bytes Sent Percent",
        bar=True,
        stack=True,
        symbolic_x=True,
        sort_x_key=lambda x: (int(x.split(",")[0][1:]),int(x.split(",")[1]),str(x.split(",")[2:-1])),
        output_dir=f"outputs/{notebook_name}/"
        
    )
     

    role_df = get_role_df(df, role=1)
    role_df = add_combined_column(role_df, ['vallen','number_of_clusters',"benchmark"], 'num_peers_vallen')
    role_df_complete = complete_multiindex(role_df, ['typ', 'vallen','number_of_clusters',"num_peers_vallen"])

    role_df_complete = add_percent_column(role_df_complete, 'num_peers_vallen', 'bytes_sent', 'bytes_sent_percent')
    plot_tikz(
        role_df_complete,
        x_col="num_peers_vallen",
        y_col="bytes_sent_percent",
        cat_col="typ",
        filename=f"outputs/{notebook_name}/geobft-spread-over-azs-bytes-sent-role1-{cluster_num_peers}.tex",
        xlabel="(Number of Peers, Vallen)",
        ylabel="Bytes Sent Percent",
        bar=True,
        stack=True,
        symbolic_x=True,
        sort_x_key=lambda x: (int(x.split(",")[0][1:]),int(x.split(",")[1]),str(x.split(",")[2:-1])),
        output_dir=f"outputs/{notebook_name}/"
    )

/mnt/c/Users/Andre/OneDrive/Cloud-Native Byzantine Consensus/code/CloudModuBFT/src/evaluation/notebooks/utils/benchmark.py:372: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Cluster Num Peers: 3.0
[np.str_('(512,2,multileader non-optimistic-2-buckets)'), np.str_('(512,2,not-alternating-non-optimistic)'), np.str_('(512,4,multileader non-optimistic-2-buckets)'), np.str_('(512,4,not-alternating-non-optimistic)'), np.str_('(512,6,multileader non-optimistic-2-buckets)'), np.str_('(512,6,not-alternating-non-optimistic)'), np.str_('(4096,2,multileader non-optimistic-2-buckets)'), np.str_('(4096,2,not-alternating-non-optimistic)'), np.str_('(4096,4,multileader non-optimistic-2-buckets)'), np.str_('(4096,4,not-alternating-non-optimistic)'), np.str_('(4096,6,multileader non-optimistic-2-buckets)'), np.str_('(4096,6,not-alternating-non-optimistic)')]
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./outputs/05-multileader/geobft-spread-over-azs-bytes-sent-role2-3.0.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-01-22>
(/usr/share/texlive/texmf-dist/tex/latex/standalone/standalone.cls
Document Class: standalone 2022/10/10 v1.3b Class to compile TeX sub-files stan
dalone
(/usr/share/texlive/texmf-dist/tex/latex/tools/shellesc.sty)
(/usr/share/texlive/texmf-dist/tex/generic/iftex/ifluatex.sty
(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(/usr/share/texlive/texmf-dist/tex/latex/standalone/standalone.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/pgf.revision.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeyslibraryfiltered
.code.tex)) (/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdftex.def
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.de
f)))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.
tex)) (/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/mathcolor.ltx))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonomet
ric.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerari
thmetics.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfint.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.
code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformation
s.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex
)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65
.sty)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18
.sty)) (/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgffor.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/math/pgfmath.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarytopaths.code.tex))))
(/usr/share/texlive/texmf-dist/tex/latex/pgfplots/pgfplots.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.revision.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgfplotssysgeneric.code
.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgfplotslibrary.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_loader.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryfpu.code.tex
)
Package pgfplots: loading complementary utilities for your pgf version...

(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgfutil-common-lists.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotslists
tructure.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotslists
tructureext.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsarray
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsmatri
x.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstableshare
d.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsdeque
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.code.te
x
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.data.co
de.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.verb.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgflibrarypgfplots.sur
fshading.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgflibrarypgfplots.surf
shading.pgfsys-pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolormap.code.
tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolor.code.tex
))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsstackedplots.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsplothandlers.code.t
ex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplothandler.cod
e.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplotimage.code.
tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.scaling.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscoordprocessing.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.errorbars.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.markers.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsticks.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.paths.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduledecorations.cod
e.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.pathmorphing.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrary
decorations.pathmorphing.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.pathreplacing.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrary
decorations.pathreplacing.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.co
ntourlua.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibraryplotmarks.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplotmarks.co
de.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.fi
llbetween.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/tikzlibraryfillb
etween.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibraryintersections.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryintersection
s.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/tikzlibrarydecor
ations.softclip.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/pgflibraryfillbe
tween.code.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.de
corations.softclip.code.tex))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
No file geobft-spread-over-azs-bytes-sent-role2-3.0.aux.
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
Package pgfplots notification 'compat/show suggested version=true': document ha
s been generated with the most recent feature set (\pgfplotsset{compat=1.18}).

[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
(outputs/05-multileader//geobft-spread-over-azs-bytes-sent-role2-3.0.aux) )</us
r/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></usr/shar
e/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on outputs/05-multileader//geobft-spread-over-azs-bytes-sent-rol
e2-3.0.pdf (1 page, 29851 bytes).
Transcript written on outputs/05-multileader//geobft-spread-over-azs-bytes-sent
-role2-3.0.log.
[np.str_('(512,2,multileader non-optimistic-2-buckets)'), np.str_('(512,2,not-alternating-non-optimistic)'), np.str_('(512,4,multileader non-optimistic-2-buckets)'), np.str_('(512,4,not-alternating-non-optimistic)'), np.str_('(512,6,multileader non-optimistic-2-buckets)'), np.str_('(512,6,not-alternating-non-optimistic)'), np.str_('(4096,2,multileader non-optimistic-2-buckets)'), np.str_('(4096,2,not-alternating-non-optimistic)'), np.str_('(4096,4,multileader non-optimistic-2-buckets)'), np.str_('(4096,4,not-alternating-non-optimistic)'), np.str_('(4096,6,multileader non-optimistic-2-buckets)'), np.str_('(4096,6,not-alternating-non-optimistic)')]

/mnt/c/Users/Andre/OneDrive/Cloud-Native Byzantine Consensus/code/CloudModuBFT/src/evaluation/notebooks/utils/benchmark.py:372: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./outputs/05-multileader/geobft-spread-over-azs-bytes-sent-role1-3.0.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-01-22>
(/usr/share/texlive/texmf-dist/tex/latex/standalone/standalone.cls
Document Class: standalone 2022/10/10 v1.3b Class to compile TeX sub-files stan
dalone
(/usr/share/texlive/texmf-dist/tex/latex/tools/shellesc.sty)
(/usr/share/texlive/texmf-dist/tex/generic/iftex/ifluatex.sty
(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(/usr/share/texlive/texmf-dist/tex/latex/standalone/standalone.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/pgf.revision.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeyslibraryfiltered
.code.tex)) (/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdftex.def
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.de
f)))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.
tex)) (/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/mathcolor.ltx))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonomet
ric.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerari
thmetics.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfint.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.
code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformation
s.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex
)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65
.sty)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18
.sty)) (/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgffor.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/math/pgfmath.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarytopaths.code.tex))))
(/usr/share/texlive/texmf-dist/tex/latex/pgfplots/pgfplots.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.revision.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgfplotssysgeneric.code
.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgfplotslibrary.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_loader.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryfpu.code.tex
)
Package pgfplots: loading complementary utilities for your pgf version...

(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgfutil-common-lists.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotslists
tructure.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotslists
tructureext.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsarray
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsmatri
x.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstableshare
d.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsdeque
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.code.te
x
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.data.co
de.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.verb.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgflibrarypgfplots.sur
fshading.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgflibrarypgfplots.surf
shading.pgfsys-pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolormap.code.
tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolor.code.tex
))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsstackedplots.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsplothandlers.code.t
ex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplothandler.cod
e.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplotimage.code.
tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.scaling.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscoordprocessing.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.errorbars.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.markers.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsticks.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.paths.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduledecorations.cod
e.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.pathmorphing.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrary
decorations.pathmorphing.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.pathreplacing.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrary
decorations.pathreplacing.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.co
ntourlua.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibraryplotmarks.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplotmarks.co
de.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.fi
llbetween.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/tikzlibraryfillb
etween.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibraryintersections.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryintersection
s.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/tikzlibrarydecor
ations.softclip.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/pgflibraryfillbe
tween.code.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.de
corations.softclip.code.tex))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
No file geobft-spread-over-azs-bytes-sent-role1-3.0.aux.
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
Package pgfplots notification 'compat/show suggested version=true': document ha
s been generated with the most recent feature set (\pgfplotsset{compat=1.18}).

[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
(outputs/05-multileader//geobft-spread-over-azs-bytes-sent-role1-3.0.aux) )</us
r/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></usr/shar
e/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on outputs/05-multileader//geobft-spread-over-azs-bytes-sent-rol
e1-3.0.pdf (1 page, 29682 bytes).
Transcript written on outputs/05-multileader//geobft-spread-over-azs-bytes-sent
-role1-3.0.log.
Cluster Num Peers: 6.0
[np.str_('(512,2,multileader non-optimistic-2-buckets)'), np.str_('(512,2,multileader non-optimistic-4-buckets)'), np.str_('(512,2,not-alternating-non-optimistic)'), np.str_('(512,4,multileader non-optimistic-2-buckets)'), np.str_('(512,4,multileader non-optimistic-4-buckets)'), np.str_('(512,4,not-alternating-non-optimistic)'), np.str_('(512,6,multileader non-optimistic-2-buckets)'), np.str_('(512,6,multileader non-optimistic-4-buckets)'), np.str_('(512,6,not-alternating-non-optimistic)'), np.str_('(4096,2,multileader non-optimistic-2-buckets)'), np.str_('(4096,2,multileader non-optimistic-4-buckets)'), np.str_('(4096,2,not-alternating-non-optimistic)'), np.str_('(4096,4,multileader non-optimistic-2-buckets)'), np.str_('(4096,4,multileader non-optimistic-4-buckets)'), np.str_('(4096,4,not-alternating-non-optimistic)'), np.str_('(4096,6,multileader non-optimistic-2-buckets)'), np.str_('(4096,6,multileader non-optimistic-4-buckets)'), np.str_('(4096,6,not-alternating-non-optimistic)')]

/mnt/c/Users/Andre/OneDrive/Cloud-Native Byzantine Consensus/code/CloudModuBFT/src/evaluation/notebooks/utils/benchmark.py:372: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./outputs/05-multileader/geobft-spread-over-azs-bytes-sent-role2-6.0.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-01-22>
(/usr/share/texlive/texmf-dist/tex/latex/standalone/standalone.cls
Document Class: standalone 2022/10/10 v1.3b Class to compile TeX sub-files stan
dalone
(/usr/share/texlive/texmf-dist/tex/latex/tools/shellesc.sty)
(/usr/share/texlive/texmf-dist/tex/generic/iftex/ifluatex.sty
(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(/usr/share/texlive/texmf-dist/tex/latex/standalone/standalone.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/pgf.revision.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeyslibraryfiltered
.code.tex)) (/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdftex.def
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.de
f)))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.
tex)) (/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/mathcolor.ltx))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonomet
ric.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerari
thmetics.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfint.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.
code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformation
s.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex
)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65
.sty)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18
.sty)) (/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgffor.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/math/pgfmath.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarytopaths.code.tex))))
(/usr/share/texlive/texmf-dist/tex/latex/pgfplots/pgfplots.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.revision.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgfplotssysgeneric.code
.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgfplotslibrary.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_loader.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryfpu.code.tex
)
Package pgfplots: loading complementary utilities for your pgf version...

(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgfutil-common-lists.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotslists
tructure.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotslists
tructureext.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsarray
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsmatri
x.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstableshare
d.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsdeque
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.code.te
x
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.data.co
de.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.verb.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgflibrarypgfplots.sur
fshading.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgflibrarypgfplots.surf
shading.pgfsys-pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolormap.code.
tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolor.code.tex
))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsstackedplots.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsplothandlers.code.t
ex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplothandler.cod
e.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplotimage.code.
tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.scaling.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscoordprocessing.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.errorbars.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.markers.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsticks.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.paths.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduledecorations.cod
e.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.pathmorphing.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrary
decorations.pathmorphing.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.pathreplacing.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrary
decorations.pathreplacing.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.co
ntourlua.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibraryplotmarks.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplotmarks.co
de.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.fi
llbetween.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/tikzlibraryfillb
etween.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibraryintersections.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryintersection
s.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/tikzlibrarydecor
ations.softclip.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/pgflibraryfillbe
tween.code.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.de
corations.softclip.code.tex))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
No file geobft-spread-over-azs-bytes-sent-role2-6.0.aux.
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
Package pgfplots notification 'compat/show suggested version=true': document ha
s been generated with the most recent feature set (\pgfplotsset{compat=1.18}).

[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
(outputs/05-multileader//geobft-spread-over-azs-bytes-sent-role2-6.0.aux) )</us
r/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></usr/shar
e/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on outputs/05-multileader//geobft-spread-over-azs-bytes-sent-rol
e2-6.0.pdf (1 page, 30630 bytes).
Transcript written on outputs/05-multileader//geobft-spread-over-azs-bytes-sent
-role2-6.0.log.
[np.str_('(512,2,multileader non-optimistic-2-buckets)'), np.str_('(512,2,multileader non-optimistic-4-buckets)'), np.str_('(512,2,not-alternating-non-optimistic)'), np.str_('(512,4,multileader non-optimistic-2-buckets)'), np.str_('(512,4,multileader non-optimistic-4-buckets)'), np.str_('(512,4,not-alternating-non-optimistic)'), np.str_('(512,6,multileader non-optimistic-2-buckets)'), np.str_('(512,6,multileader non-optimistic-4-buckets)'), np.str_('(512,6,not-alternating-non-optimistic)'), np.str_('(4096,2,multileader non-optimistic-2-buckets)'), np.str_('(4096,2,multileader non-optimistic-4-buckets)'), np.str_('(4096,2,not-alternating-non-optimistic)'), np.str_('(4096,4,multileader non-optimistic-2-buckets)'), np.str_('(4096,4,multileader non-optimistic-4-buckets)'), np.str_('(4096,4,not-alternating-non-optimistic)'), np.str_('(4096,6,multileader non-optimistic-2-buckets)'), np.str_('(4096,6,multileader non-optimistic-4-buckets)'), np.str_('(4096,6,not-alternating-non-optimistic)')]
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.

/mnt/c/Users/Andre/OneDrive/Cloud-Native Byzantine Consensus/code/CloudModuBFT/src/evaluation/notebooks/utils/benchmark.py:372: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

entering extended mode
(./outputs/05-multileader/geobft-spread-over-azs-bytes-sent-role1-6.0.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-01-22>
(/usr/share/texlive/texmf-dist/tex/latex/standalone/standalone.cls
Document Class: standalone 2022/10/10 v1.3b Class to compile TeX sub-files stan
dalone
(/usr/share/texlive/texmf-dist/tex/latex/tools/shellesc.sty)
(/usr/share/texlive/texmf-dist/tex/generic/iftex/ifluatex.sty
(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(/usr/share/texlive/texmf-dist/tex/latex/standalone/standalone.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/pgf.revision.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeyslibraryfiltered
.code.tex)) (/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdftex.def
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.de
f)))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.
tex)) (/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/mathcolor.ltx))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonomet
ric.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerari
thmetics.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfint.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.
code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformation
s.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex
)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65
.sty)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18
.sty)) (/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgffor.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/math/pgfmath.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarytopaths.code.tex))))
(/usr/share/texlive/texmf-dist/tex/latex/pgfplots/pgfplots.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.revision.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgfplotssysgeneric.code
.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgfplotslibrary.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_loader.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryfpu.code.tex
)
Package pgfplots: loading complementary utilities for your pgf version...

(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgfutil-common-lists.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotslists
tructure.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotslists
tructureext.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsarray
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsmatri
x.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstableshare
d.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsdeque
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.code.te
x
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.data.co
de.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.verb.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgflibrarypgfplots.sur
fshading.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgflibrarypgfplots.surf
shading.pgfsys-pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolormap.code.
tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolor.code.tex
))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsstackedplots.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsplothandlers.code.t
ex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplothandler.cod
e.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplotimage.code.
tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.scaling.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscoordprocessing.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.errorbars.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.markers.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsticks.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.paths.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduledecorations.cod
e.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.pathmorphing.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrary
decorations.pathmorphing.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarydecorations.pathreplacing.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrary
decorations.pathreplacing.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.co
ntourlua.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibraryplotmarks.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplotmarks.co
de.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.fi
llbetween.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/tikzlibraryfillb
etween.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibraryintersections.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryintersection
s.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/tikzlibrarydecor
ations.softclip.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfcontrib/pgflibraryfillbe
tween.code.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.de
corations.softclip.code.tex))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
No file geobft-spread-over-azs-bytes-sent-role1-6.0.aux.
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
Package pgfplots notification 'compat/show suggested version=true': document ha
s been generated with the most recent feature set (\pgfplotsset{compat=1.18}).

[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
(outputs/05-multileader//geobft-spread-over-azs-bytes-sent-role1-6.0.aux) )</us
r/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></usr/shar
e/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on outputs/05-multileader//geobft-spread-over-azs-bytes-sent-rol
e1-6.0.pdf (1 page, 30296 bytes).
Transcript written on outputs/05-multileader//geobft-spread-over-azs-bytes-sent
-role1-6.0.log.

In [202]:
output_dir=f"outputs/{notebook_name}/"
s = ""
for filename in os.listdir(output_dir):
    if filename.endswith(".tex"):
        tex_content = "%"+filename+"\n"
        with open(os.path.join(output_dir, filename), 'r') as f:
            for line in f:
                tex_content += line
                
            

        s+= "\n"+tex_content+"\n"

with open(f"outputs/{notebook_name}/figures.tex", 'w') as f:
    f.write(s)